import Navbar from "./components/Misc/Navbar";
import OverlayNavbar from "./components/Misc/OverlayNavbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-main-bg relative font-body">
        <Navbar />
        {children}
        <OverlayNavbar />
      </body>
    </html>
  );
}
